# frontend/.github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - main # зөвхөн main branch-д push хийхэд ажиллана

jobs:
  # ---------------- TEST JOB ----------------
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Cypress тестийг ажиллуулах
      - name: Run Cypress Tests
        run: npm run test
        env:
          NEXT_PUBLIC_API_URL: https://test.technospace.site

  # ---------------- DEPLOY JOB ----------------
  deploy:
    runs-on: ubuntu-latest
    needs: test # зөвхөн test амжилттай бол ажиллана

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Frontend Build & Push
      - name: Build and Push Frontend
        run: |
          docker build -t abylai123/frontend:latest .
          docker push abylai123/frontend:latest

      # Deploy frontend container on server
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/my-app
            # Зөвхөн frontend container-г update хийнэ
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml pull frontend
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d frontend
            docker image prune -f
